# Generated by Django 4.2.7 on 2024-01-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='category/'),
            preserve_default=False,
        ),
    ]
