# Generated by Django 4.2.7 on 2024-01-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='bio',
            new_name='message',
        ),
    ]
