# Generated by Django 4.2.7 on 2024-01-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_bio_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now=True)),
                ('img', models.ImageField(upload_to='feature/')),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
