# Generated by Django 4.2.7 on 2024-01-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_sen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lorem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
