# Generated by Django 4.2.7 on 2024-01-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('status', models.CharField(max_length=700)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='busin/')),
            ],
        ),
    ]
