# Generated by Django 4.2.7 on 2024-01-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='img',
        ),
    ]
