# Generated by Django 4.2.7 on 2024-01-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
