# Generated by Django 4.2.7 on 2024-01-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_sit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('status', models.CharField(max_length=9000)),
                ('date', models.DateField(auto_now=True)),
                ('bio', models.CharField(max_length=9000)),
                ('image', models.ImageField(upload_to='ipsum/')),
            ],
        ),
    ]
