# Generated by Django 4.2.7 on 2024-01-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_ipsum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipsum',
            name='bio',
        ),
    ]
