# Generated by Django 4.2.7 on 2024-01-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_ipsum_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='slug',
            field=models.SlugField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
